name: Build max-htlc-fee-rate
on:
  workflow_dispatch:
  push:
    paths:
      - 'max-htlc-fee-rate**'
      - '.github/workflows/build_max-htlc-fee-rate.yaml'
    branches:
      - master
    tags:        
      - '*'
jobs:
  build:
    env:
      REGISTRY: ghcr.io
      IMAGENAME: max-htlc-fee-rate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: Docker build
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ${{ env.IMAGENAME }}
        registry: ${{ env.REGISTRY }}
        directory: max-htlc-fee-rate
        dockerfile: max-htlc-fee-rate/Dockerfile
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
